spring:
#禁用thymeleaf模板缓存, 也可以禁用其他缓存
  thymeleaf:    cache: false
#使用profile进行配置
  profiles:
    active: production

#生成密钥, 没成功
#keytool -genkey -alias jwt -keyalg RSA -keysize 1024 -keystore jwt.jks -validity 365

#server:
#  port: 8443
#  ssl:
#    key-store: classpath:mykeys.jks
#    key-store-password: letmein
#    key-password: letmein

#设置日志, 输出到文件没成功
#logging:
#  file:
#    path: classpath:bookworm.log
#  level:
#    root: WARN
#    org:
#      springframework:
#        security: DEBUG

